[workspace]
resolver = "2"
members = [
    "binding",
    "canvas",
    "canvas_events",
    "curves",
    "draw",
    "render",
    "render_canvas",
    "render_software",
    "render_gl_offscreen",
    "scene",
]


[workspace.dependencies]
flo_canvas = { path = "./canvas" }
flo_canvas_events = { path = "./canvas_events" }
flo_render = { path = "./render" }
flo_render_canvas = { path = "./render_canvas" }
flo_render_gl_offscreen = { path = "./render_gl_offscreen" }
flo_draw = { path = "./draw" }
flo_curves = { path = "./curves" }
flo_binding = { path = "./binding" }
flo_scene = { path = "./scene" }
desync = { path = "./desync" }

# allsorts is very slow when built for debug, so packages using flo_draw should consider optimising it even in debug builds
[profile.dev.package.allsorts]
opt-level = 2
